language: go
go:
  - 1.9.x
before_install:
  - sudo add-apt-repository ppa:masterminds/glide
  - sudo apt-get update
  - sudo apt-get install -y glide
install:
  - glide install
script:
  - go test -v -race
